### ISSUE TITLE
Create a confidential variant of ERC-3643 security token standard using Zama's fhEVM

### ISSUE THREAD

**Issue by zaccherinij** [zama-ai/bounty-program#128]
## Overview
The goal of this bounty is to explore and implement how the specific capabilities of Zama's fhEVM can enhance and improve the functionality of the ERC-3643 security token standard for security tokens. Participants will leverage the encrypted types and FHE operations supported by the fhEVM to create a confidential variant of this security token standard.

## What we expect
First, the bounty participants should get familiar with the [ERC-3643 standard](https://eips.ethereum.org/EIPS/eip-3643) as well as its current [official implementation](https://github.com/TokenySolutions/T-REX/tree/main). Notice that this standard also relies on a decentralized identity standard such as ERC 735 via the [OnchainID implementation](https://github.com/onchain-id/solidity), which could also be adapted to the fhEVM by adding confidentiality.

### Judging criteria
- **Smart Contract:** The smart contracts need to be written in Solidity running on the fhEVM. The code should be cleanly commented, with adherence (as close as possible) to the standard is important.
- **Testing:** Testing smart contracts using hardhat is also highly recommended.
- **Deployment:** The smart contract should be compatible with Zama's fhEVM devnet. 
- **Use of fhEVM:** The contract should employ hidden information, showcasing the capabilities of the fhEVM. Care should be taken by the bounty hunter to decide which state variables to encrypt and which should stay unencrypted. Suggestions (non-exhaustive) of state variables to encrypt:  transfer amounts, allowances, number of frozen tokens, identities such as country codes, etc.
- **Bonus points:** Implement an additional contract to showcase a concrete scenario for security settlements, leveraging the confidential security token. For instance, DVP (Delivery Vs Payment) or DVD (Delivery Vs Delivery), and so on. (Here are some [examples](https://github.com/jat9292/sc-bonds-dvp-cadmos) from an old hackathon on DVP using a different security token standard for inspiration)

### 🥇Best submission: up to €5,000.
To be considered best submission, a solution must be efficient, effective and demonstrate a deep understanding of the core problem. Alongside the technical correctness, it should also be submitted with a clean code, clear explanations and a complete documentation.

### 🥈Second-best submission: up to €3,000.
For a solution to be considered the second best submission, it should be both efficient and effective. The code should be neat and readable, while its documentation might not be as exhaustive as the best submission, it should cover the key aspects of the solution.

### 🥉Third-best submission: up to €2,000.
The third best submission is one that presents a solution that effectively tackles the challenge at hand, even if it may have certain areas of improvement in terms of efficiency or depth of understanding. Documentation should be present, covering the essential components of the solution.

Reward amounts are decided based on code quality, model accuracy scores and speed performance on a m6i.metal AWS server. When multiple solutions of comparable scope are submitted they are compared based on the accuracy metrics and computation times.

## Related links and references
- [Confidential variant of ERC 20](https://github.com/zama-ai/fhevm-contracts/blob/main/contracts/token/ERC20/EncryptedERC20.sol) for fhEVM specific sources.
- [Compliant ERC20](https://github.com/zama-ai/fhevm/tree/main/examples/Identity) with confidential decentralized identities and its corresponding [blog post](https://www.zama.ai/post/programmable-privacy-and-onchain-compliance-using-homomorphic-encryption).
- [Zama's fhEVM documentation](https://docs.zama.ai/fhevm)

### Step 1: Registration
Click [here](https://www.zama.ai/join-the-zama-bounty-program) to register for the fhEVM Bounty. Fill out the registration form with your information. Once you fill out the form, you will receive a confirmation email with a link to the submission portal for when you are ready to submit your code.
>[!Note]
>Check your spam folder in case you don't receive the confirmation email. If you haven't received it within 24 hour, please contact us by email at bounty@zama.ai.

### Step 2: Work on the Challenge
Read through the Bounty details and requirements carefully. Use the provided resources and create your own GitHub repository to store your code. 
If you have any questions during your work, feel free to comment directly in the Bounty issue and our team will be happy to assist you.

### Step 3: Submission
Once you have completed your work, upload your completed work to the submission portal using the link provided in the confirmation email.

>[!Note]
>The deadline for submission is **September, 8th 2024** (Midnight, Anywhere On Earth). Late submissions will not be considered.

We wish you the best of luck with the challenge!

## ✅ Support
- Comment on this issue with any questions regarding this bounty.
- Email for private questions: bounty@zama.ai
- Join the Zama community channels [here](https://zama.ai/community).

**Comment by 0xalexbel** [comment]
As pointed out in the bounty description, the ERC3643 standard relies on an on-chain Identity verification mechanism. Would it be ok to take advantage of the fhevm internal coprocessor feature to. perfom the following:
- store sensitive encrypted data on-chain
- implement an adapted version of the identity `isClaimValid(...)` function (the identity contract would store the input handles, the claim issuer would keep the inputProof) ?

```solidity
// Here is the copressor verifyCiphertext() function 
IFHEVMCoprocessor(fhevmCoprocessorAdd).verifyCiphertext(
            inputHandle,
            msg.sender,
            inputProof,
            bytes1(toType)
        );
``` 

```solidity
// Here is the original IIdentity.sol claim verification function profile
function isClaimValid(
        IIdentity _identity,
        uint256 claimTopic,
        bytes calldata sig,
        bytes calldata data)
```

**Comment by immortal-tofu** [comment]
"We don't view inputs as data to store on-chain, so we wouldn't recommend this approach for various reasons. Specifically, the ZKPoK is meant to be verified by a specific contract with a specific user (msg.sender). Note that, currently, ZKPoKs are not implemented, but we have already implemented the API in the fhevmjs/fhevm libraries.

That said, a good approach would likely be to store an identity contract on-chain where all sensitive data is accessible only to the contract and the user. The identity contract could, with user consent, allow a specific contract to access certain data or attestations.

**Comment by immortal-tofu** [comment]
As mentioned in the bounty description:

> The contract should employ hidden information, showcasing the capabilities of the fhEVM. Care should be taken by the bounty hunter to decide which state variables to encrypt and which should stay unencrypted. Suggestions (non-exhaustive) of state variables to encrypt: transfer amounts, allowances, number of frozen tokens, identities such as country codes, etc.

So, it's up to you. Since fhEVM allows the storage of encrypted data on-chain, storing sensitive data on-chain makes sense instead of using an off-chain mechanism.
If you want to store a string, we introduced `ebytes256` in fhEVM 0.5.0. It's not documented yet, but it works like the `eaddress` type, with only the `TFHE.eq` and `TFHE.ne` operators available.
Regarding gas costs, we aim to have a gas-efficient solution, meaning the contract should avoid any unnecessary operations, especially on encrypted types.

Overall, the idea is to provide a contract using fhEVM capabilities and explain the reasoning behind the choices made.

**Comment by 0xalexbel** [comment]
Hi Zama Team! I'm trying to access the zama-dev node to test my contracts prior to submission by following the doc instructions (i created a metamask wallet and followed the instructions). On the faucet page a copy pasted my metamask wallet address and i keep reading "You exceeded ... wait for 11h" What shall I do ? Second question: for the bounty i need several wallets for several roles, how can I acheive this on the zama-dev node ? Thank you for your help!

**Comment by mohitrakhade20** [comment]
Just want to know if this bounty program is still available and can I do the contributions?
