### ISSUE TITLE
Create an on-chain game that keeps private states hidden using Zama's fhEVM programmable privacy

### ISSUE THREAD

**Issue by zaccherinij** [zama-ai/bounty-program#81]
## Overview

Design and develop an on-chain game that can keep the private states hidden thanks to the unique features of Zama's fhEVM programmable privacy.

### How to participate?
1️⃣ Register [here](https://zama.ai/bounty-program).
2️⃣ When ready, submit your code [here](https://zama.ai/bounty-program).
🗓️ Submission deadline: December 17, 2023.

## What we expect

Unlike ZK-based privacy systems, FHE ensures that data remains available on-chain while still maintaining composability. This is particularly beneficial for applications like games, which are typically multi-party interaction systems where privacy is crucial. Our blockchain product, the fhEVM, illustrates this by enhancing the Ethereum Virtual Machine (EVM) with FHE capabilities, allowing computations on encrypted data without revealing its content. It's up to you to determine the best game to design that leverages these capabilities.

### Requirements:
* **Smart Contract**: Write a smart contract in Solidity that encapsulates the game logic
* **UI Interface**: Create a user-friendly UI for game interaction.
* **Deployment**: The smart contract should be compatible with the Zama fhEVM devnet.
* **Use of fhEVM**: The game should employ hidden information, showcasing the capabilities of the fhEVM. The game should be distinctive in a way that would be challenging or impossible without fhEVM's features.

### Judging Criteria:
* **Use of Zama's fhEVM**: Effectiveness in demonstrating the unique features of the Zama's fhEVM.
* **Fun Factor**: The game's overall enjoyment and user engagement.
* **Submission Quality**: Emphasis on clear code and polished UI.

### 🥇Best submission: up to €10,000.
To be considered best submission, a solution must be efficient, effective and demonstrate a deep understanding of the core problem. Alongside the technical correctness, it should also be submitted with a clean code, clear explanations and a complete documentation.

### 🥈Second-best submission: up to €3,500.
For a solution to be considered the second best submission, it should be both efficient and effective. The code should be neat and readable, while its documentation might not be as exhaustive as the best submission, it should cover the key aspects of the solution.

### 🥉Third-best submission: up to €1,500.
The third best submission is one that presents a solution that effectively tackles the challenge at hand, even if it may have certain areas of improvement in terms of efficiency or depth of understanding. Documentation should be present, covering the essential components of the solution.

## Related links and references

- [fhEVM repository](https://github.com/zama-ai/fhevm)
- [fhEVM documentation](https://docs.zama.ai/fhevm)
- [Confidential ERC20 Blog post](https://www.zama.ai/post/confidential-erc-20-tokens-using-homomorphic-encryption)
- [On-chain Blind Auctions Blog post](https://www.zama.ai/post/on-chain-blind-auctions-using-homomorphic-encryption)

## Questions?
Do you have a specific question about this bounty or Zama's fhEVM? 
- Join the live conversation on the [FHE.org discord server](https://discord.fhe.org/) 
- Ask technical question on our [Community forum](https://community.zama.ai)
- Join the general discussion on the Telegram group: [fhEVM explorers](https://t.me/+Ojt5y-I7oR42MTkx)
- And feel free to reach out privately at: bounty@zama.ai

**Comment by aquint-zama** [comment]
### Winners

🥇 1st place: A [submission](https://github.com/kroist/encryptedWords) by [Kroist](https://github.com/kroist)
🥈 2nd place A [submission](https://github.com/Aditya-Chaurasia11/ZAMA-handcricket) by [Aditya-Chaurasia11](https://github.com/Aditya-Chaurasia11)
🥉 3rd place : A [submission](https://github.com/joeyiny/FRAMED/) by  [Joeyiny](https://github.com/joeyiny)
