### ISSUE TITLE
Create a String Library That Works on Encrypted Data Using TFHE-rs

### ISSUE THREAD

**Issue by tomtau** [zama-ai/bounty-program#83]
# Zama Bounty Program Application

- Bounty Github Link: https://github.com/zama-ai/bounty-program/issues/80

- Github username: tomtau

- About you: I'm a software engineer and researcher (an alumnus of [HKU PL Group](https://hkuplg.github.io/)). I learned about Zama from reddit and from the main website, I came across the Bounty Program. I am new to TFHE and this would be my first contribution to the Zama Bounty Program.

**Comment by aquint-zama** [comment]
Hello @tomtau , nice to see you joining our bounty program, we try a new registering process for Season 4 (to avoid tons of issues in this repo). Will it be possible for you to register [here](https://zama.ai/bounty-program) please 🙏 
Once done you could close this issue.
