### ISSUE TITLE
Create a String Library That Works on Encrypted Data Using TFHE-rs

### ISSUE THREAD

**Issue by MakisChristou** [zama-ai/bounty-program#85]
# Zama Bounty Program Application

- Bounty Github Link: https://github.com/zama-ai/bounty-program/issues/80

- Github username: MakisChristou

- About you: I am a software engineer currently working in the Web3 domain, specifically with the Ethereum ecosystem and its tools. In ~2019 I learned about FHE and was fascinated by it although It didn't seem practical at the time. I recently learned about Zama through LinkedIn and was intrigued by the use of FHE for real world applications and specifically that it was a relatively straightforward to use Rust implementation. I found about the bounty program though the official website and decided that I could contribute. This is my first attempt at any bounty program.

# Terms and conditions

If your contribution is accepted, we need you to read and sign our Terms and Conditions below to get rewarded:

- [for individuals](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=d5453e6d-fa39-48ba-aba8-2ac1c81613d8&env=eu&acct=3f0c0a1c-6d14-4ca1-946b-19567fbc8f39&v=2);
- [or for companies](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=68dd1e8c-4ab5-46af-b811-6298863ab87f&env=eu&acct=3f0c0a1c-6d14-4ca1-946b-19567fbc8f39&v=2).

**Comment by aquint-zama** [comment]
Hello @MakisChristou, nice to see you joining our bounty program, we try a new registering process for Season 4 (to avoid tons of issues in this repo). Will it be possible for you to register [here](https://zama.ai/bounty-program) please 🙏 
Once done you could close this issue.

**Comment by MakisChristou** [comment]
Just registered, but I added the whole [link to my profile]( https://github.com/MakisChristou) in the Github username section. I hope thats okay.

**Comment by aquint-zama** [comment]
perfect thank you!
