### ISSUE TITLE
Create an on-chain game that keeps private states hidden using Zama's fhEVM programmable privacy

### ISSUE THREAD

**Issue by MikeHatchi** [zama-ai/bounty-program#86]
# Zama Bounty Program Application

- Bounty Github Link: https://github.com/zama-ai/bounty-program/issues/81

- Github username: mikehatchi

- About you:
Machine/Deep learning and blockchain developer at https://www.vrona.io, connecting the dots with cryptography.
I've taken part in bounty 3 on concrete-ml (FHE.Chess).

I've learned about Zama bounty program when I was participating at FileCoin and Medusanet (see Protocol Labs) hackathon. I was searching encryption protocol on blockchain on Zama.AI.
I previously knew about Zama on 2021/2022 while searching solution to infer (computer vision) on encrypted data.

**Comment by aquint-zama** [comment]
hi @MikeHatchi, we slightly changed the application workflow (to make it easier) you just need to register to https://www.zama.ai/bounty-program, is it possible for you to register there and then I'll close this issue.

Thank you!

**Comment by MikeHatchi** [comment]
Hello @aquint-zama >>> done.
